# Setup
title:               Razon o fe
tagline:             'Comunidad Atea'
description:         'Una comunidad para conocer, compartir y cuidar. Queremos promover y compartir una visión racional, filosófica, crítica, científica y ética de la vida.'
url:                 http://localhost:4000
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Razon o fe
  url:               https://twitter.com/razonofe
  email:             razonofe@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
