name: Jekyll site CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
        cp -r -v ${{ github.workspace }}/_site/* ${{ github.workspace }}/
        pwd
        ls -lha ${{ github.workspace }}
    - name: Add and Commit changes to gh-pages branch
      run: |
        cd ${{ github.workspace }}
        git status
        git config --local user.email 'action@github.com'
        git config --local user.name 'GitHub Action'
        git pull
        git add -A .
        git commit -m 'Updates compiled site files'
        git status
        echo before checkout gh-pages...
        git checkout gh-pages
        git merge master
        git status
        echo before push...
        git push -f